import { ChainConfig, ChainId, ChainKey, DexType } from "../types";

export const CHAIN_CONFIGS: Record<ChainId, ChainConfig> = {
  [ChainId.ETHEREUM]: {
    chainId: ChainId.ETHEREUM,
    key: "mainnet",
    name: "Ethereum",
    wrappedNativeSymbol: "WETH",
    explorerUrl: "https://etherscan.io",
    supportedDexes: [DexType.UNISWAP_V3, DexType.SUSHISWAP_V3, DexType.PANCAKESWAP_V3],
    publicRpcUrl: "https://eth.merkle.io",
  },
  [ChainId.BSC]: {
    chainId: ChainId.BSC,
    key: "bsc",
    name: "BNB Smart Chain",
    wrappedNativeSymbol: "WBNB",
    explorerUrl: "https://bscscan.com",
    supportedDexes: [DexType.UNISWAP_V3, DexType.SUSHISWAP_V3, DexType.PANCAKESWAP_V3],
    publicRpcUrl: "https://bsc-dataseed.binance.org",
  },
  [ChainId.POLYGON]: {
    chainId: ChainId.POLYGON,
    key: "polygon",
    name: "Polygon",
    wrappedNativeSymbol: "WPOL",
    explorerUrl: "https://polygonscan.com",
    supportedDexes: [DexType.UNISWAP_V3, DexType.SUSHISWAP_V3],
    publicRpcUrl: "https://polygon-rpc.com",
  },
  [ChainId.ARBITRUM]: {
    chainId: ChainId.ARBITRUM,
    key: "arbitrum",
    name: "Arbitrum",
    wrappedNativeSymbol: "WETH",
    explorerUrl: "https://arbiscan.io",
    supportedDexes: [DexType.UNISWAP_V3, DexType.SUSHISWAP_V3, DexType.PANCAKESWAP_V3],
    publicRpcUrl: "https://arb1.arbitrum.io/rpc",
  },
  [ChainId.AVALANCHE]: {
    chainId: ChainId.AVALANCHE,
    key: "avalanche",
    name: "Avalanche",
    wrappedNativeSymbol: "WAVAX",
    explorerUrl: "https://snowtrace.io",
    supportedDexes: [DexType.UNISWAP_V3, DexType.SUSHISWAP_V3],
    publicRpcUrl: "https://api.avax.network/ext/bc/C/rpc",
  },
  // Superchains
  [ChainId.OPTIMISM]: {
    chainId: ChainId.OPTIMISM,
    key: "optimism",
    name: "Optimism",
    wrappedNativeSymbol: "WETH",
    explorerUrl: "https://optimistic.etherscan.io",
    supportedDexes: [DexType.UNISWAP_V3, DexType.SUSHISWAP_V3, DexType.VELODROME],
    publicRpcUrl: "https://mainnet.optimism.io",
  },
  [ChainId.BASE]: {
    chainId: ChainId.BASE,
    key: "base",
    name: "Base",
    wrappedNativeSymbol: "WETH",
    explorerUrl: "https://basescan.org",
    supportedDexes: [DexType.UNISWAP_V3, DexType.SUSHISWAP_V3, DexType.PANCAKESWAP_V3, DexType.AERODROME],
    publicRpcUrl: "https://mainnet.base.org",
  },
  [ChainId.ZORA]: {
    chainId: ChainId.ZORA,
    key: "zora",
    name: "Zora",
    wrappedNativeSymbol: "WETH",
    explorerUrl: "https://explorer.zora.energy",
    supportedDexes: [DexType.UNISWAP_V3],
    publicRpcUrl: "https://rpc.zora.energy",
  },
  [ChainId.UNICHAIN]: {
    chainId: ChainId.UNICHAIN,
    key: "unichain",
    name: "Unichain",
    wrappedNativeSymbol: "WETH",
    explorerUrl: "https://uniscan.xyz",
    supportedDexes: [DexType.UNISWAP_V3],
    publicRpcUrl: "https://mainnet.unichain.org",
  },
  [ChainId.WORLD_CHAIN]: {
    chainId: ChainId.WORLD_CHAIN,
    key: "worldchain",
    name: "World Chain",
    wrappedNativeSymbol: "WETH",
    explorerUrl: "https://worldscan.org",
    supportedDexes: [DexType.UNISWAP_V3],
    publicRpcUrl: "https://worldchain-mainnet.g.alchemy.com/public",
  },
  [ChainId.SONEIUM]: {
    chainId: ChainId.SONEIUM,
    key: "soneium",
    name: "Soneium",
    wrappedNativeSymbol: "WETH",
    explorerUrl: "https://soneium.blockscout.com",
    supportedDexes: [DexType.UNISWAP_V3],
    publicRpcUrl: "https://rpc.soneium.org",
  },
};

export const CHAIN_KEY_TO_ID: Record<ChainKey, ChainId> = {
  mainnet: ChainId.ETHEREUM,
  bsc: ChainId.BSC,
  polygon: ChainId.POLYGON,
  arbitrum: ChainId.ARBITRUM,
  avalanche: ChainId.AVALANCHE,
  // Superchains
  optimism: ChainId.OPTIMISM,
  base: ChainId.BASE,
  zora: ChainId.ZORA,
  unichain: ChainId.UNICHAIN,
  worldchain: ChainId.WORLD_CHAIN,
  soneium: ChainId.SONEIUM,
};
