// AUTO-GENERATED by scripts

import { ChainId } from "../types";

export interface TokenDeployment {
  address: `0x${string}`;
  decimalsOverride?: number;
}

export type TokenDeployments = Partial<Record<ChainId, TokenDeployment>>;

export const TOKEN_DEPLOYMENTS: Record<string, TokenDeployments> = {
  WETH: {
    [ChainId.ETHEREUM]: { address: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2" },
    [ChainId.BSC]: { address: "0x2170ed0880ac9a755fd29b2688956bd959f933f8" },
    [ChainId.POLYGON]: { address: "0x7ceb23fd6bc0add59e62ac25578270cff1b9f619" },
    [ChainId.ARBITRUM]: { address: "0x82af49447d8a07e3bd95bd0d56f35241523fbab1" },
    [ChainId.AVALANCHE]: { address: "0x49d5c2bdffac6ce2bfdb6640f4f80f226bc10bab" },
    [ChainId.OPTIMISM]: { address: "0x4200000000000000000000000000000000000006" },
    [ChainId.BASE]: { address: "0x4200000000000000000000000000000000000006" },
    [ChainId.ZORA]: { address: "0x4200000000000000000000000000000000000006" },
    [ChainId.UNICHAIN]: { address: "0x4200000000000000000000000000000000000006" },
    [ChainId.WORLD_CHAIN]: { address: "0x4200000000000000000000000000000000000006" },
    [ChainId.SONEIUM]: { address: "0x4200000000000000000000000000000000000006" },
  },

  USDC: {
    [ChainId.ETHEREUM]: { address: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48" },
    [ChainId.BSC]: { address: "0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d", decimalsOverride: 18 },
    [ChainId.POLYGON]: { address: "0x3c499c542cef5e3811e1192ce70d8cc03d5c3359" },
    [ChainId.ARBITRUM]: { address: "0xaf88d065e77c8cc2239327c5edb3a432268e5831" },
    [ChainId.AVALANCHE]: { address: "0xb97ef9ef8734c71904d8002f8b6bc66dd9c48a6e" },
    [ChainId.OPTIMISM]: { address: "0x0b2c639c533813f4aa9d7837caf62653d097ff85" },
    [ChainId.BASE]: { address: "0x833589fcd6edb6e08f4c7c32d4f71b54bda02913" },
    [ChainId.UNICHAIN]: { address: "0x078d782b760474a361dda0af3839290b0ef57ad6" },
    [ChainId.WORLD_CHAIN]: { address: "0x79a02482a880bce3f13e09da970dc34db4cd24d1" },
  },

  USDT: {
    [ChainId.ETHEREUM]: { address: "0xdac17f958d2ee523a2206206994597c13d831ec7" },
    [ChainId.BSC]: { address: "0x524bc91dc82d6b90ef29f76a3ecaabafffd490bc" },
    [ChainId.POLYGON]: { address: "0x9417669fbf23357d2774e9d421307bd5ea1006d2" },
    [ChainId.AVALANCHE]: { address: "0x9702230a8ea53601f5cd2dc00fdbc13d4df4a8c7" },
    [ChainId.OPTIMISM]: { address: "0x94b008aa00579c1307b0ef2c499ad98a8ce58e58" },
    [ChainId.BASE]: { address: "0xfde4c96c8593536e31f229ea8f37b2ada2699bb2" },
    [ChainId.UNICHAIN]: { address: "0x588ce4f028d8e7b53b687865d6a67b3a54c75518" },
    [ChainId.SONEIUM]: { address: "0x3a337a6ada9d885b6ad95ec48f9b75f197b5ae35" },
  },

  WBTC: {
    [ChainId.ETHEREUM]: { address: "0x2260fac5e5542a773aa44fbcfedf7c193bc2c599" },
    [ChainId.BSC]: { address: "0x0555e30da8f98308edb960aa94c0db47230d2b9c" },
    [ChainId.ARBITRUM]: { address: "0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f" },
    [ChainId.AVALANCHE]: { address: "0x0555e30da8f98308edb960aa94c0db47230d2b9c" },
    [ChainId.OPTIMISM]: { address: "0x68f180fcce6836688e9084f035309e29bf0a2095" },
    [ChainId.BASE]: { address: "0x0555e30da8f98308edb960aa94c0db47230d2b9c" },
    [ChainId.WORLD_CHAIN]: { address: "0x03c7054bcb39f7b2e5b2c7acb37583e32d70cfa3" },
    [ChainId.SONEIUM]: { address: "0x0555e30da8f98308edb960aa94c0db47230d2b9c" },
  },

  DAI: {
    [ChainId.ETHEREUM]: { address: "0x6b175474e89094c44da98b954eedeac495271d0f" },
    [ChainId.BSC]: { address: "0x1af3f329e8be154074d8769d1ffa4ee058b1dbc3" },
    [ChainId.POLYGON]: { address: "0x8f3cf7ad23cd3cadbd9735aff958023239c6a063" },
    [ChainId.ARBITRUM]: { address: "0xda10009cbd5d07dd0cecc66161fc93d7c9000da1" },
    [ChainId.AVALANCHE]: { address: "0xd586e7f844cea2f87f50152665bcbc2c279d8d70" },
    [ChainId.OPTIMISM]: { address: "0xda10009cbd5d07dd0cecc66161fc93d7c9000da1" },
    [ChainId.BASE]: { address: "0x50c5725949a6f0c72e6c4a641f24049a917db0cb" },
  },

  CBETH: {
    [ChainId.ETHEREUM]: { address: "0xbe9895146f7af43049ca1c1ae358b0541ea49704" },
    [ChainId.POLYGON]: { address: "0x4b4327db1600b8b1440163f667e199cef35385f5" },
    [ChainId.ARBITRUM]: { address: "0x1debd73e752beaf79865fd6446b0c970eae7732f" },
    [ChainId.OPTIMISM]: { address: "0xaddb6a0412de1ba0f936dcaeb8aaa24578dcf3b2" },
    [ChainId.BASE]: { address: "0x2ae3f1ec7f1f5012cfeab0185bfc7aa3cf0dec22" },
  },

  RETH: {
    [ChainId.ETHEREUM]: { address: "0xae78736cd615f374d3085123a210448e74fc6393" },
    [ChainId.POLYGON]: { address: "0x0266f4f08d82372cf0fcbccc0ff74309089c74d1" },
    [ChainId.ARBITRUM]: { address: "0xec70dcb4a1efa46b8f2d97c310c9c4790ba5ffa8" },
    [ChainId.OPTIMISM]: { address: "0x9bcef72be871e61ed4fbbc7630889bee758eb81d" },
    [ChainId.BASE]: { address: "0xb6fe221fe9eef5aba221c348ba20a1bf5e73624c" },
    [ChainId.UNICHAIN]: { address: "0x94cac393f3444cef63a651ffc18497e7e8bd036a" },
  },

  STETH: {
    [ChainId.ETHEREUM]: { address: "0xae7ab96520de3a18e5e111b5eaab095312d7fe84" },
  },

  WAVAX: {
    [ChainId.POLYGON]: { address: "0x2c89bbc92bd86f8075d1decc58c7f4e0107f286b" },
    [ChainId.AVALANCHE]: { address: "0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7" },
  },

  WBNB: {
    [ChainId.BSC]: { address: "0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c" },
    [ChainId.AVALANCHE]: { address: "0x264c1383ea520f73dd837f915ef3a732e204a493" },
  },

  WPOL: {
    [ChainId.POLYGON]: { address: "0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270" },
  },

  WSTETH: {
    [ChainId.ETHEREUM]: { address: "0x7f39c581f595b53c5cb19bd0b3f8da6c935e2ca0" },
    [ChainId.BSC]: { address: "0x26c5e01524d2e6280a48f2c50ff6de7e52e9611c" },
    [ChainId.POLYGON]: { address: "0x03b54a6e9a984069379fae1a4fc4dbae93b3bccd" },
    [ChainId.ARBITRUM]: { address: "0x5979d7b546e38e414f7e9822514be443a4800529" },
    [ChainId.OPTIMISM]: { address: "0x1f32b1c2345538c0c6f582fcb022739c4a194ebb" },
    [ChainId.BASE]: { address: "0xc1cba3fcea344f92d9239c08c0568f6f2f0ee452" },
    [ChainId.UNICHAIN]: { address: "0xc02fe7317d4eb8753a02c35fe019786854a92001" },
  },

};
