// AUTO-GENERATED by scripts

export interface TokenMetadata {
  name: string;
  decimals: number;
}

export const TOKEN_METADATA: Record<string, TokenMetadata> = {
  WETH: { name: "WETH", decimals: 18 },
  USDC: { name: "USDC", decimals: 6 },
  USDT: { name: "Tether", decimals: 6 },
  WBTC: { name: "Wrapped Bitcoin", decimals: 8 },
  DAI: { name: "Dai", decimals: 18 },
  CBETH: { name: "Coinbase Wrapped Staked ETH", decimals: 18 },
  RETH: { name: "Rocket Pool ETH", decimals: 18 },
  STETH: { name: "Lido Staked Ether", decimals: 18 },
  WAVAX: { name: "Bridged WAVAX", decimals: 18 },
  WBNB: { name: "Wrapped BNB", decimals: 18 },
  WPOL: { name: "Wrapped POL", decimals: 18 },
  WSTETH: { name: "Wrapped stETH", decimals: 18 },
};
